# Arithmetic Operators: +, -, *, /

by using ufunc additional arguments like, where, dtype and out.

here now we will use add()

In [1]:
import numpy as np

In [2]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([20, 21, 22, 23, 24, 25])
xnew = np.add(x, x2)
xnew

array([30, 32, 34, 36, 38, 40])

In [3]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([20, 21, 22, 23, 24, 25])
xnew = np.subtract(x, x2)
xnew

array([-10, -10, -10, -10, -10, -10])

In [4]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([20, 21, 22, 23, 24, 25])
xnew = np.multiply(x, x2)
xnew

array([200, 231, 264, 299, 336, 375])

In [5]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([20, 21, 22, 23, 24, 25])
xnew = np.divide(x, x2)
xnew

array([0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333,
       0.6       ])

power() function raises the value from the 1st array to the power of the values of the 2nd array and return the results in a new array.

In [6]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([3, 5, 6, 8, 2, 33])
xnew = np.power(x, x2)
xnew

array([                1000,               161051,              2985984,
                  815730721,                  196, -2081117049324899825])

remainder - mod() and remainder() functions return the remainder of the 1st array corresponding to the 2nd array and result in the new array.

In [7]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([20, 21, 22, 23, 24, 25])
xnew = np.mod(x, x2)
xnew

array([10, 11, 12, 13, 14, 15])

In [8]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([20, 21, 22, 23, 24, 25])
xnew = np.remainder(x, x2)
xnew

array([10, 11, 12, 13, 14, 15])

Quotient and mod(remainder)

the divmod() function return both the quotient and mod.

7 / 3

2 - Quotient

1 - Mod

In [9]:
x = np.array([10, 11, 12, 13, 14, 15])
x2 = np.array([20, 21, 22, 23, 24, 25])
xnew = np.divmod(x, x2)
xnew

(array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))

absolute() and abs() - do the same operation but here we  should use absolute() to avoid confusion with python with in-built function math.abs()

In [10]:
x = np.array([-10, -11, -12, -13, -14, -15])
xnew = np.abs(x)
xnew

array([10, 11, 12, 13, 14, 15])