# Rounding Decimals

There are 5 ways of rounding of the decimals in numpy: truncation, fix, rounding, floor, ceil.

In [1]:
import numpy as np

## truncation: trunc() an fix()

here we are truncating the below array, these command remove the decimals and return the float number closest to zero.

In [3]:
x = np.trunc([-3.66, 3.65])
x

array([-3.,  3.])

In [4]:
x = np.fix([-3.66, 3.65])
x

array([-3.,  3.])

## rounding: around()

the around() function increments preceding digit or decimal by nearest to 1: if n>5 = 1 or n<5 = 0.

In [6]:
x = np.around(3.166, 2)
x

np.float64(3.17)

floor() - round of the decimals to the lower integer.

In [7]:
x = np.floor([-3.16, 3.67])
x

array([-4.,  3.])

ciel() - round of the decimals to the upper integer.

In [8]:
x = np.ceil([-3.16, 3.67])
x

array([-3.,  4.])