# Summations

diffference addition is done beween 2 arguments whereas summation happens over n elements.

In [1]:
import numpy as np

Adding the 2 Array.

In [2]:
x = np.array([1, 2, 3])
x1 = np.array([1, 2, 3])
xnew = np.add(x, x1)
xnew

array([2, 4, 6])

Sum the values in 2 array

In [3]:
x = np.array([1, 2, 3])
x1 = np.array([1, 2, 3])
xnew = np.sum([x, x1])
xnew

np.int64(12)

Summation over an axis: if you specify axis=1, numpy will sum the number in each array.

In [ ]:
x = np.array([1, 2, 3])
x1 = np.array([1, 2, 3])
xnew = np.sum([x, x1], axis=1)
xnew

array([6, 6])

Cummulative sum: means partially adding the element in array.

example: [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 2, 6, 10] represent by cumsum()

In [5]:
x = np.array([1, 2, 3])
xnew = np.cumsum(x)
xnew

array([1, 3, 6])