## Numpy Data types

data types in python: String, Integer, Float, Boolean, Complex

- `i`: Integer
- `b`: Boolean
- `u`: Unsigned Integer
- `f`: Float
- `c`: Complex Float
- `m`: TimeDelta
- `M`: DateTime
- `O`: Object
- `S`: String
- `U`: Unicode String
- `V`: Memory

## Checking the data type of numpy array - dtype

In [1]:
import numpy as np
x =  np.array([1, 2, 3, 4, 5])

In [2]:
x

array([1, 2, 3, 4, 5])

In [3]:
x.dtype

dtype('int64')

In [4]:
x =  np.array(['apple', 'banana', 'chickoo'])
x.dtype

dtype('<U7')

In [5]:
x =  np.array([1, 2, 3, 4, 5], dtype='S')
x.dtype

dtype('S1')

In [6]:
x =  np.array([1, 2, 3, 4, 5], dtype='i4')
x.dtype

dtype('int32')

If a type in which the elements cannot be casted then numpy will raise error. What if a value cannot be converted?

In [7]:
x = np.array(['a', '2', '3'], dtype='i')
x.dtype

ValueError: invalid literal for int() with base 10: 'a'

## Converting data type in existing array - astype()

Floating data type -> Integer data type

In [8]:
x = np.array([1.1, 2.1, 3.1])
x1 = x.astype('i') # x.astype(int)
x1

array([1, 2, 3], dtype=int32)

In [9]:
x2 = x.astype(int)
x2, x1

(array([1, 2, 3]), array([1, 2, 3], dtype=int32))

In [11]:
x2.dtype

dtype('int64')

Integer data type -> Boolean data type

In [12]:
ib = np.array([1, 0, 3])
ib1 = ib.astype(bool)
ib1, ib1.dtype

(array([ True, False,  True]), dtype('bool'))