## Shape of Array

The Shape of an array is the number of elements in each dimensions.

Try to get shape of any array

In [1]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [2]:
y = np.array([[[11, 12], [21, 22], [31, 32]], [4, 5, 6]])
y.shape

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.

In [3]:
z = np.array([[[11, 12], [21, 22], [31, 32]], [[41, 42], [51, 52], [61, 62]]])
z.shape

(2, 3, 2)

Now we will create a %-D Array using ndmin

In [4]:
x = np.array([1,2, 3], ndmin=5)
x, x.ndim

(array([[[[[1, 2, 3]]]]]), 5)

In [5]:
x.shape

(1, 1, 1, 1, 3)

## Reshaping

Shape of an Array like adding or removing the elements.

### 1D -> 2D

In [6]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
x = x.reshape(4, 3)

In [7]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 1D -> 3D

In [8]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
x = x.reshape(2, 3, 2)
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### Error in Reshaping

3 and 3 shape elements required in the Array

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = x.reshape(3, 3)
x

ValueError: cannot reshape array of size 8 into shape (3,3)

### Return Copy or View

In [10]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x.reshape(2, 4).base

array([1, 2, 3, 4, 5, 6, 7, 8])

### Unknown Dimension

When wedon't know about the how dimension will be create from the data means we have no number to pass as dimension that time we called it unknown dimension and pass -1 as value.

You are only allowed to have one unknown dimension. pass -1

In [11]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x.reshape(2, 2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [12]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x.reshape(2, 2, -1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Flattening

Converting Multi-Dimension to 1D Array

In [13]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = x.reshape(-1)
x

array([1, 2, 3, 4, 5, 6])

There are a lot of functions for changing the shape of an Array in numpy like `flatten`, `ravel`, also some are rearranging element functions like `rot90`, `flip`, `fliplr`, `flipud`. They all are actually comes under advanced numpy.