# Joining Array

Here for this we will pass `concatenate()`

In [1]:
import numpy as np

### Joining 1D Array

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate((x, y))

array([1, 2, 3, 4, 5, 6])

### Joining 2D Array

In [3]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Joining Array using Stack Function

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.stack((x, y), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

### Stacking along with rows: `hstack()`

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.hstack((x, y))

array([1, 2, 3, 4, 5, 6])

### Stacking along with columns: `vstack()`

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.vstack((x, y))

array([[1, 2, 3],
       [4, 5, 6]])

### Stacking along with Height(depth): `dstack()`

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.dstack((x, y))

array([[[1, 4],
        [2, 5],
        [3, 6]]])