# Array Spliting, Searching, Sorting and Filter

## Array Spliting

Spliting arrays in numpy - It is reverse to joining, breaking the array using `array_split()`

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, 6])
xnew = np.array_split(x, 3)
xnew

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
xnew = np.array_split(x, 4)
xnew

[array([1, 2]), array([3, 4]), array([5]), array([6])]

Access splitted array using index.

In [4]:
x = np.array([1, 2, 3, 4, 5, 6])
xnew = np.array_split(x, 3)
xnew[0], xnew[1], xnew[2]

(array([1, 2]), array([3, 4]), array([5, 6]))

### Spliting 2D Array

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
xnew = np.array_split(x, 3)
xnew[0], xnew[1], xnew[2]

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

Split 2D array into three 2D Array

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
xnew = np.array_split(x, 3)
xnew[0], xnew[1], xnew[2]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]]))

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
xnew = np.array_split(x, 3, axis=1)
xnew

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

Alternate solution is using the `hsplit()`, opposite `hstack()`

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
xnew = np.hsplit(x, 3)
xnew

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
xnew = np.hstack(x)
xnew

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

## Array Searching

Searching arrays in numpy - you can search an array for a certain value and return the indexs that get the match by using `where()`

In [10]:
x = np.array([1, 2, 3, 4, 5, 4, 5, 4])
xnew = np.where(x == 4)
xnew

(array([3, 5, 7]),)

Find the Even number from the array

In [11]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xnew = np.where(x%2 == 0)
xnew

(array([1, 3, 5, 7, 9]),)

Find the Odd number from the array

In [12]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xnew = np.where(x%2 == 1)
xnew

(array([0, 2, 4, 6, 8]),)

Search Sorted using `searchsorted()` - perform binary search in array. we will now find the index where the value 7 should be insterted.

In [13]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xnew = np.searchsorted(x, 7)
xnew

np.int64(6)

Search Sorted from the right side using `searchsorted()` and `side="right"`

In [14]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xnew = np.searchsorted(x, 7, side="right")
xnew

np.int64(7)

How to search multiple value.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xnew = np.searchsorted(x, [7, 5, 9])
xnew

array([6, 4, 8])

## Array Sorting

Sorting arrays in numpy - ndarray object has a function which is called `sort()`, and this will sort a specified array.

In [16]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
xnew = np.sort(x)
xnew

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Sort the array alphabetically

In [17]:
x = np.array(["apple", "watermelon", "banana", "mango", "melon", "chickoo", "pineapple"])
xnew = np.sort(x)
xnew

array(['apple', 'banana', 'chickoo', 'mango', 'melon', 'pineapple',
       'watermelon'], dtype='<U10')

Sort the boolean array

In [18]:
x = np.array([True, False, True, True, False, False])
xnew = np.sort(x)
xnew

array([False, False, False,  True,  True,  True])

Sort the 2D array

In [19]:
x = np.array([[3, 2, 4], [5, 0, 1]])
xnew = np.sort(x)
xnew

array([[2, 3, 4],
       [0, 1, 5]])

## Array Filter

Filter array - Getting some elements out of an existing array and creating a new array is called filtering.

A boolean index list is a list of boolean co-responding to indexes in the array. (True and False)

Create an array from the element on index 0 to 2

In [20]:
x = np.array([41, 42, 43, 44])
x1 = np.array([True, False, True, True])
xnew = x[x1]
xnew

array([41, 43, 44])

Now we will create a filter array that will return only values higher than 42.

In [22]:
x = np.array([41, 42, 43, 44])
x1 = []
for i in x:
    if i > 42:
        x1.append(True)
    else:
        x1.append(False)
xnew = x[x1]
x1, xnew

([False, False, True, True], array([43, 44]))

Create a filter array that will return only even elements from the original array.

In [23]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
x1 = []
for i in x:
    if i%2 == 0:
        x1.append(True)
    else: x1.append(False)
xnew = x[x1]
x1, xnew

([False, True, False, True, False, True, False], array([2, 4, 6]))

Yes, you can also create filter directly from the array that will return only values higher than 42.

In [24]:
x = np.array([41, 12, 35, 56, 58, 95, 65])
x1 = x > 42
x1

array([False, False, False,  True,  True,  True,  True])

In [25]:
xnew = x[x1]
xnew

array([56, 58, 95, 65])

Yes, you can also create filter directly from the array that will return only values even numbers.

In [26]:
x = np.array([41, 12, 35, 56, 58, 95, 65])
x1 = x%2 == 0
x1

array([False,  True, False,  True,  True, False, False])

In [27]:
xnew = x[x1]
xnew

array([12, 56, 58])