# Random numbers

Random meaning - Something that cannot be predicted logically.

In [1]:
from numpy import random

In [2]:
x = random.randint(100)
x

88

You can also generates `float()` via `rand()` from 0 to 1

In [3]:
x = random.rand()
x

0.04029005717393108

You can also generate random Array.

Generate 1D array containing 5 random int from 0 to 100

In [4]:
x = random.randint(100, size=5)
x

array([26, 27, 90, 53, 25])

Generate 2D array containing 5 random int from 0 to 100

In [5]:
x = random.randint(100, size=(2, 5))
x

array([[ 4, 50, 61,  8, 69],
       [32,  5, 20, 20, 11]])

Generate 1D array containing 5 random float

In [6]:
x = random.rand(5)
x

array([0.25270665, 0.27868701, 0.15984995, 0.23884504, 0.48532189])

Generate 2D array containing 5 random float

In [7]:
x = random.rand(3, 5)
x

array([[0.49384477, 0.8536983 , 0.59313906, 0.23441337, 0.67881168],
       [0.69932283, 0.72965471, 0.45225888, 0.84494714, 0.582259  ],
       [0.47318752, 0.14968321, 0.48419198, 0.78269108, 0.53303482]])

You can also generate random numbers from an array `choice()`

In [8]:
x = random.choice([3, 5, 7, 9, 1, 4, 6])
x

np.int64(9)

You can also generate random numbers from an 2D array `choice()`

In [9]:
x = random.choice([3, 5, 7, 9, 1, 4, 6], size=(3, 5))
x

array([[9, 9, 1, 9, 4],
       [4, 3, 6, 1, 5],
       [3, 5, 9, 1, 1]])