In [3]:
import numpy as np
np.__version__

'2.1.1'

## Creating a numpy ndarray object
- `ndarray`: array in the numpy called ndarray

```py
np.array()
```

In [6]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [7]:
type(x)

numpy.ndarray

List, Tuple or any array like Object pass in np.array() convert to ndarray.

In [10]:
y = np.array((1,  2, 3, 4, 5, 6))
y

array([1, 2, 3, 4, 5, 6])

In [9]:
type(y)

numpy.ndarray

Dimensions in Array means level of depth in array.
- `0D`: 10
- `1D`: [1, 2, 3]
- `2D`: [[1, 2, 3], [1, 2, 3]]
- `3D`: [[[1], [2]], [[3], [4, 5]]]

## OD Array

In [13]:
x = np.array(10)
x, type(x)

(array(10), numpy.ndarray)

In [12]:
type(x)

numpy.ndarray

## 1D Array

In [14]:
x = np.array([1, 2, 3])
x, type(x)

(array([1, 2, 3]), numpy.ndarray)

## 2D Array

In [15]:
x = np.array([[1, 2], [3, 4]])
x, type(x)

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray)

## 3D Array

In [17]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [8, 9]]])
x, type(x)

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [8, 9]]]),
 numpy.ndarray)

`Structure of the array must be same for all level array means 2 by 2 - 2 row, 2 column`

## Check the ndarray dimentions (ndim)

```py
ndarray_var.ndim
```

In [18]:
x.ndim

3

## Converting Dimention of the ndarray

```py
np.array([1, 2, 3, 4, 5], ndimn=5)
```

In [20]:
x = np.array([1, 2, 3, 4, 5], ndmin=5)
x, x.ndim

(array([[[[[1, 2, 3, 4, 5]]]]]), 5)

## Indexing of the Array

```py
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x[0, 2]
x[1][3]
```

In [21]:
x[0, 0, 0, 0, 2]

np.int64(3)

In [22]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [23]:
x[0]

np.int64(1)

In [24]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
x[0]

array([1, 2, 3, 4, 5])

In [26]:
x[0, 1]

np.int64(2)

In [27]:
x[0][2]

np.int64(3)

## Slicing of the Array

```py
x = np.array([1, 2, 3, 4, 5])
# Simple Slicing
x[1:3]

# Ending Slicing
x[2:]

# Starting Slicing
x[:3]

# Negative Slicing
x[-3:-1]

# Step Slicing
x[0:4:2]

# Step Slicing from entire array
x[::3]

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#Simple Slicing
x[1:, 2:]
```

In [28]:
x = np.array([1, 2, 3, 4, 5])
x[1:3]

array([2, 3])

In [29]:
x[2:]

array([3, 4, 5])

In [30]:
x[:2]

array([1, 2])

In [47]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
x[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
x[1][2:4]

array([8, 9])

In [36]:
x[1:][2:]

array([], shape=(0, 5), dtype=int64)

In [48]:
x[0:1, 2:]

array([[3, 4, 5]])

In [38]:
x[0:1][2:4]

array([], shape=(0, 5), dtype=int64)

In [39]:
x[0][2:4]

array([3, 4])

In [40]:
x[2][2:4]

array([13, 14])

In [41]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[1:8:2]

array([2, 4, 6, 8])

In [43]:
x[1:8:3]

array([2, 5, 8])

In [44]:
x[::2]

array([1, 3, 5, 7, 9])

## 2D Array Slicing

```py
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Simple Slicing
x[1:, 2:] # [[8, 9, 10]]
x[0:, 2:] # array([], shape=(0, 5), dtype=int64)
```

In [49]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
x[1:][2:]

array([], shape=(0, 5), dtype=int64)

In [51]:
x[1:, 2:]

array([[ 8,  9, 10]])

In [52]:
x[0:][2:]

array([], shape=(0, 5), dtype=int64)

In [59]:
x[0:1][0]

array([1, 2, 3, 4, 5])

In [58]:
x[0:1, 1]

array([2])

In [60]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
x[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [63]:
x[0:, 1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])